version: '3.8'

networks:
  personalblog:
    name: personalblog
volumes:
  certbot-etc:
  wordpress:
  db-data:
services:
  mydb:
    image: mariadb:10.6.18
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - personalblog
  wordpress:
    depends_on:
      - mydb
    image: wordpress:6.6-fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME:  ${MYSQL_DATABASE}
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - personalblog
  
  wpphp:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: wpphp
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - personalblog

  wp-nginx:
    depends_on:
      - wordpress
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: wp-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html
      - ./certbot-etc:/etc/letsencrypt
    networks:
      - personalblog
  wpcertbot:
    depends_on:
      - wp-nginx
    image: certbot/certbot
    container_name: wpcertbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email sammy@your_domain --agree-tos --no-eff-email --staging -d your_domain -d www.your_domain


